server:
  port: ${GATEWAY_SERVER_PORT}

spring:
  datasource:
    driver-class-name:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

eureka:
  instance:
    hostname: ${EUREKA_HOST}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${EUREKA_SERVER_PORT}/eureka/

api:
  url:
    auth: ${AUTH_API_URL}:${AUTH_PORT}
    customer: ${CUSTOMER_API_URL}:${CUSTOMER_PORT}
    standard-instrument: ${STANDARD_INSTRUMENT_API_URL}:${STANDARD_INSTRUMENT_PORT}
    calibration: ${CALIBRATION_API_URL}:${CALIBRATION_PORT}
    device: ${DEVICE_API_URL}:${DEVICE_PORT}


