server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: web-service-gateway

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/

api:
  url:
    customer: ${CUSTOMER_API_URL:localhost:8082}
    device: ${DEVICE_API_URL:localhost:8083}